services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=America/Chicago
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /srv/docker/crafty/backups:/crafty/backups
        - /srv/docker/crafty/logs:/crafty/logs
        - /srv/docker/crafty/servers:/crafty/servers
        - /srv/docker/crafty/config:/crafty/app/config
        - /srv/docker/crafty/import:/crafty/import
