services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=America/Chicago #optional
    volumes:
      - config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: no

volumes:
  config: