services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - FIREFOX_CLI=https://duckduckgo.com/ #optional
    volumes:
      - config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: no

volumes:
  config: